default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: true
  pool: 25
  username: your name
  password: your passwrod
  host: localhost

development:
  <<: *default
  database: rssreader_dev

test:
  <<: *default
  database: rssreader_test


production:
  <<: *default
  database: rssreader
