#CREATE DATABASE rssreader CHARACTER SET latin1 COLLATE utf8mb4_unicode_ci;

default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 25
  username: your name
  password: your passwrod
  host: localhost

development:
  <<: *default
  database: rssreader_dev

test:
  <<: *default
  database: rssreader_test


production:
  <<: *default
  database: rssreader
